name: "train_on_attacks"
description: "original experiment with pgd adversarial training"
dataset: 'mnist'
batch_size: 512
patch_size: 4
vocab_size: 1024
model:
    patcher_type: 'conv_disjoint'
    tokenizer_type: 'mlp'
    tokenizer_hidden_layers: [64, 128]
train:
    toktrain_epochs: 2
    train_epochs: 50
    delta: 0.1